---
title: "clustering dataset"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(gridExtra)
```

full dataset analysis
```{r}
getwd()
setwd("C:/Users/Laurens/Downloads")

df <- read_csv("rawtrips3_prepared2_clustered2 (1).csv")

prop.table(table(df$insurance))

mean(df$tripduration) #6.4

tt4 <- table(df$car)
prop.table(tt4) #20.5% car

prop.table(table(df$hotel)) 

mean(df$purchaseLag) #14.44

prop.table(table(df$registered))

df$children <- as.factor(df$children)

df$seats <- as.factor(df$seats)
```

Visualizations
```{r}
#clusters vs pop on LOG_tripduration & LOG_purchaseLag
g1 <- ggplot(data=df,aes(x=cluster_labels, y=LOG_tripduration)) +
  geom_boxplot() +
  stat_summary(fun.y=mean, geom='point', col='red', size=2) +
  geom_hline(yintercept=mean(df$LOG_tripduration), col='red')

g2 <- ggplot(data=df,aes(x=cluster_labels, y=LOG_purchaseLag)) +
  geom_boxplot() +
  stat_summary(fun.y=mean, geom='point', col='red', size=2) +
  geom_hline(yintercept=mean(df$LOG_purchaseLag), col='red')

grid.arrange(g1, g2, nrow=1)

#categoricals clusters vs pop
g3 <- ggplot(data=df, aes(x=cluster_labels, col=I('gray'), fill=summerdeparture)) +
  geom_bar(position='fill')

g4 <- ggplot(data=df, aes(x=cluster_labels, col=I('gray'), fill=weekenddeparture)) +
  geom_bar(position='fill')

g5 <- ggplot(data=df, aes(x=cluster_labels, col=I('gray'), fill=children)) +
  geom_bar(position='fill')

g6 <- ggplot(data=df, aes(x=cluster_labels, col=I('gray'), fill=seats)) +
  geom_bar(position='fill')

grid.arrange(g3, g4, g5, g6, nrow=2, ncol=2)

```


cluster0 analysis
```{r}
cluster0 <- df %>%
  filter(cluster_labels=='cluster_0')

mean(cluster3$age) 

prop.table(table(cluster0$children))

prop.table(table(cluster0$seats))

prop.table(table(cluster0$gender))

mean(cluster0$tripduration) 

mean(cluster0$purchaseLag)

prop.table(table(cluster0$car))

prop.table(table(cluster0$insurance))

prop.table(table(cluster0$hotel)) 

prop.table(table(cluster0$departuremonth))

prop.table(table(cluster0$summerdeparture))

prop.table(table(cluster0$weekenddeparture))
```

cluster1 analysis
```{r}
cluster1 <- df %>%
  filter(cluster_labels=='cluster_1')

mean(cluster1$age) 

prop.table(table(cluster1$children))

prop.table(table(cluster1$seats))

prop.table(table(cluster1$gender))

mean(cluster1$tripduration) 

mean(cluster1$purchaseLag)

prop.table(table(cluster1$car))

prop.table(table(cluster1$insurance))

prop.table(table(cluster1$hotel)) 

prop.table(table(cluster1$departuremonth))

prop.table(table(cluster1$summerdeparture))

prop.table(table(cluster1$weekenddeparture))

```

cluster2 analysis
```{r}
cluster2 <- df %>%
  filter(cluster_labels=='cluster_2')

mean(cluster2$age) 

prop.table(table(cluster2$children))

prop.table(table(cluster2$seats))

prop.table(table(cluster2$gender))

mean(cluster2$tripduration) 

mean(cluster2$purchaseLag)

prop.table(table(cluster2$car))

prop.table(table(cluster2$insurance))

prop.table(table(cluster2$hotel)) 

prop.table(table(cluster2$departuremonth))

prop.table(table(cluster2$summerdeparture))

prop.table(table(cluster2$weekenddeparture))
```


Cluster3
```{r}
cluster3 <- df %>%
  filter(cluster_labels=='cluster_3')

mean(cluster3$age) 

prop.table(table(cluster3$children))

prop.table(table(cluster3$seats))

prop.table(table(cluster3$gender))

mean(cluster3$tripduration) 

mean(cluster3$purchaseLag)

prop.table(table(cluster3$car))

prop.table(table(cluster3$insurance))

prop.table(table(cluster3$hotel)) 

prop.table(table(cluster3$departuremonth))

prop.table(table(cluster3$summerdeparture))

prop.table(table(cluster3$weekenddeparture))


```

